version: '3'

services:
  weather-service-redis:
    container_name: weather-service-redis
    image: redis:latest
    ports:
      - "6379:6379"

  weather-service-api:
    container_name: weather-service-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - weather-service-redis
    environment:
      - SPRING_PROFILES_ACTIVE=test
